### ISSUE TITLE
PHP redirect will not work with new NGINX PHP

### ISSUE THREAD

**Issue by maciekpaprocki** [awsdocs/elastic-beanstalk-samples#123]
file:
https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/security-configuration/https-redirect/php/https-redirect-php.config

Will work only with old PHP ( non Nginx 7.3 and lower )

**Comment by phi16180** [comment]
Is there a way around the configuration file for Nginx as this one is for Apache?

**Comment by curtismorte** [comment]
Amazon Linux 2 uses Nginx by default now instead of Apache. So that config file will need to be translated to Nginx.

**Let's break this down**:
* RewriteCond %{HTTP:X-Forwarded-Proto} !https | Rewrite the URL if the X-Forwarded-Proto header is not set to https
* RewriteCond %{HTTP_USER_AGENT} !ELB-HealthChecker | Rewrite when the user agent doesn't contain ELB-HealthChecker
* RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} | The rule is make the above re-writes use HTTPS.

**On Amazon Linux 2, you can add nginx configuration files to `/etc/nginx/conf.d/elasticbeanstalk/` and they will get placed within the server directive for nginx**.

Looking at the docs from Nginx, you can do something like:
```

# Rewrite when the user agent doesn't contain ELB-HealthChecker
if ( $http_user_agent !~ 'ELB-HealthChecker' ) {
    return 301 https://$host$request_uri;
}

# Rewrite the URL if the X-Forwarded-Proto header is not set to https
if ($http_x_forwarded_proto = "http") {
    return 301 https://$host$request_uri;
}
```

I just wrote this up for you, so feel free to test it out. It should give you the basis of what you need and you can modify it from there.

**Comment by macdaddyaz** [comment]
Thanks @curtismorte . I think that first stanza results in a redirect loop. But here's the setup that worked for me.

###### .ebextensions/application-load-balancer.config

```yaml
# Configure an Application load balancer
# Start an HTTPS listener, using our ACM wildcard certificate
option_settings:
  aws:elasticbeanstalk:environment:
    LoadBalancerType: application
  aws:elbv2:listener:80:
    DefaultProcess: default
    ListenerEnabled: 'true'
    Protocol: HTTP
  aws:elbv2:listener:443:
    DefaultProcess: default
    ListenerEnabled: 'true'
    Protocol: HTTPS
    SSLCertificateArns: arn:aws:acm:us-west-2:999999999999:certificate/99999999-xxxx-9999-xxxx-999999999999
    SSLPolicy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
  aws:elasticbeanstalk:environment:process:default:
    DeregistrationDelay: '20'
    HealthCheckInterval: '60'
    HealthCheckPath: /
    HealthCheckTimeout: '5'
    HealthyThresholdCount: '3'
    UnhealthyThresholdCount: '5'
    Port: '80'
    Protocol: HTTP
    StickinessEnabled: 'false'
```
###### .platform/nginx/conf.d/elasticbeanstalk/01-force-https.conf
```yaml
# '01-' prefix to ensure this is loaded before EB's php.conf
# No idea if that makes a difference
# Rewrite the URL if the X-Forwarded-Proto header is not set to https
if ($http_x_forwarded_proto = "http") {
    return 301 https://$host$request_uri;
}
```

Would the maintainers accept a PR for this change?
