### ISSUE TITLE
Is it safe to push SSLCertificateId ARNs to source control?

### ISSUE THREAD

**Issue by ltskinner** [awsdocs/elastic-beanstalk-samples#127]
If not, is there a better way to get the config or the ARN to the elastic beanstalk instance?

I am referencing the [template here](https://github.com/awsdocs/elastic-beanstalk-samples/blob/master/configuration-files/aws-provided/security-configuration/loadbalancer-clb-securelistener.config)

Thank you!

**Comment by jpswade** [comment]
You can't really do anything with an arn without access to it's AWS account, but it could be considered sensitive in some circles.

Even though it is relatively safe, I'd like to figure out a way to avoid having it in the repo, so it could be set by the environment, as you will need a different SSL Cert per environment, if they use different domains.

**Comment by jpswade** [comment]
One idea was to try something like this:

```
option_settings:
  aws:elb:listener:443:
    SSLCertificateId: '`{"Fn::GetOptionSetting": {"Namespace": "aws:elasticbeanstalk:application:environment", "OptionName": "EB_ELB_ACM", "DefaultValue": "arn:aws:acm:us-east-2:1234567890123:certificate/####################################"}}`'
    ListenerProtocol: HTTPS
    InstancePort: 443
```

But I'm not sure it works.

**Comment by jpswade** [comment]
The way I solved it was like this:

```
option_settings:
  aws:elb:listener:443:
    SSLCertificateId:
      "Fn::GetOptionSetting":
          Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: "EB_ELB_ACM"
          DefaultValue: {"Ref":"AWS::NoValue"}
    ListenerProtocol: HTTPS
    InstancePort: 443
```
