### ISSUE TITLE
https-redirect-php don't works correctly on Amazon Linux 2 Instances

### ISSUE THREAD

**Issue by ronaldtorres** [awsdocs/elastic-beanstalk-samples#148]
The current [solution](https://github.com/awsdocs/elastic-beanstalk-samples/blob/b5e8eaea6a0acca6b80281d4f1afe408a50e1afb/configuration-files/aws-provided/security-configuration/https-redirect/php/https-redirect-php.config) just doesn't works as expected.

The folder `/etc/httpd/conf.d` is overwritten after any deploy and the file `http-redirect.conf' will be removed.

I discovered this solution for this issue:

```yml
files:
  "/tmp/http-redirect.conf":
    mode: "000644"
    owner: root
    group: root
    content: |
      RewriteEngine On
      RewriteCond %{HTTP:X-Forwarded-Proto} !https
      RewriteCond %{HTTP_USER_AGENT} !ELB-HealthChecker
      RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI}

container_commands:
  moveredirect:
    command: "sudo mv /tmp/http-redirect.conf /var/proxy/staging/httpd/conf.d/http-redirect.conf"
```

Looks like all the configuration files are created on the `/var/proxy/staging/httpd` folder and then copied to `/etc/httpd/` automatically.

I don't know if it is the best solution but this works for me now.
