### ISSUE TITLE
Change docker-compose build and run command

### ISSUE THREAD

**Issue by ngohuytrieu** [awsdocs/elastic-beanstalk-samples#166]
Hi, I am using **AWS ELB (docker)** for my production website and I am running into this stuck for days.

I need to custom a **docker-compose build and run command** into something like
```sh
docker-compose build --build-arg TARGET_ENV='dev'
docker-compose up -d
```
but couldn't get it to work. Please help

Here are solutions that I tried:

1. Configuration file with **container_command** `.ebextensions/myapp.config`

```yml
container_commands:
  01_build:
    command: "docker-compose build --build-arg TARGET_ENV='dev'"
  02_start:
    command: "docker-compose up -d"
```
2. Predeploy script
*  `.elasticbeanstalk/config.yml`
```yml
 option_settings:
   aws:elasticbeanstalk:container:predeploy:
     - source: predeploy.sh
       destination: /opt/elasticbeanstalk/hooks/appdeploy/pre
       runas: root
```
*  `.ebextensions/predeploy.sh`

```sh
#!/bin/bash

# if a command fails, the script will stop running and exit immediately
set -e

# Set execute permission on the script
chmod +x predeploy.sh

# Build the Docker image
docker-compose build --build-arg TARGET_ENV="dev"

# Start the containers
docker-compose up -d
```
