### ISSUE TITLE
Validity of securitygroup-disable-auto-use-existing.config in question

### ISSUE THREAD

**Issue by jeremyjpaws** [awsdocs/elastic-beanstalk-samples#61]
The example at:
* [https://github.com/awslabs/elastic-beanstalk-samples/blob/master/configuration-files/community-provided/security-configuration/securitygroup-disable-auto-use-existing.config](https://github.com/awslabs/elastic-beanstalk-samples/blob/master/configuration-files/community-provided/security-configuration/securitygroup-disable-auto-use-existing.config)

, seems to not work as is. The CmpFn::Remove function seems to not work, and syntax validation will fail on the non-alphanumeric parameter names.

**Comment by dankhen** [comment]
@mosheeshel (example author), would you care to check and follow up?

**Comment by amnk** [comment]
I'm hitting the same issue.

**Comment by mosheeshel** [comment]
Sorry for the very late reply. We've been continuously using this example, in production, without issues.
Can you send an example of the actual cfn file you're using?

**Comment by dankhen** [comment]
Closing for inactivity.
Anyone, feel free to reactivate and provide more info if this is still an issue.

**Comment by mosheeshel** [comment]
Sorry for dropping the ball on this. I had no chance to test it, but in our code this solution is still working - is it possible that AWS has done some changes to  beanstalk and for some (newer) accounts this is not acceptable anymore?
This solution was offered to us by AWS support some time back.

**Comment by melvynkim** [comment]
Bump.

I have the same issue.  `CmpFn::Remove` doesn't remove the existing security group. Everything else in example seems to work (e.g. adds custom security group, etc).

@mosheeshel 

Can you share some full example of how you've applied this for your production? Thanks

**Comment by mosheeshel** [comment]
Are you applying this on an existing env, or while creating a new one?
This code works for us still in production, but we never tried modifying an existing Beanstalk env, only when creating new ones. So for us, it doesn't remove anything, just prevents the creation of the default security group.

Specifically we use the following file (replaceable variable names between {{}}), we place it under the `.ebextensions` folder when creating the application version file.
```
Resources:
  AWSEBSecurityGroup: { "CmpFn::Remove" : {} }
  AWSEBAutoScalingLaunchConfiguration:
    Properties:
      SecurityGroups:  {{AUTO_SCALING_SECURITY_GROUP}}
      KeyName : "microcosm"
      ImageId: "{{AMI_IMAGE_ID}}"
  AWSEBLoadBalancer:
    Properties:
      SecurityGroups: {{ELB_SECURITY_GROUP}}
      AccessLoggingPolicy:
        EmitInterval: 5
        Enabled: true
        S3BucketName: {{ELB_ACCESS_LOG_BUCKET}}
        S3BucketPrefix: LB/{{APP}}/{{ENV}}
option_settings:
    - namespace: "aws:elb:loadbalancer"
      option_name: "SecurityGroups"
      value: {{ELB_SECURITY_GROUP}}
    - namespace: "aws:elb:loadbalancer"
      option_name: "ManagedSecurityGroup"
      value: "{{ELB_MANAGED_SECURITY_GROUP}}"
    - namespace: "aws:ec2:vpc"
      option_name: "ELBSubnets"
      value: "{{ELB_SUBNETS}}"
```

**Comment by sinpaout** [comment]
This configuration prevent security group auto creation for Load balancer.But security group for instances are still created.
```yml
option_settings:
  - namespace: "aws:elbv2:loadbalancer"
    option_name: "SecurityGroups"
    value: sg-123
  - namespace: "aws:elbv2:loadbalancer"
    option_name: "ManagedSecurityGroup"
    value: sg-123
```

**Comment by Rami-Tebechrani** [comment]
@sinpaout how can we prevent the default EC2 SG to be created? I'm already using this to add my own sg to the ec2
```
option_settings:
  - namespace: aws:autoscaling:launchconfiguration
    option_name: SecurityGroups
    value: "sg-123456"
```
