### ISSUE TITLE
AWS::CFN::Authentication example issue with custom IamInstanceProfile

### ISSUE THREAD

**Issue by taraslayshchuk** [awsdocs/elastic-beanstalk-samples#88]
This example with [`AWS::CloudFormation::Authentication`](https://github.com/awsdocs/elastic-beanstalk-samples/blob/7af44e03e42ba242a4732890f40794597a1a11f7/configuration-files/aws-provided/instance-configuration/package-oracle-jdk.config#L62) will not work in case you are passing custom IAM instance profile with [aws:autoscaling:launchconfiguration:IamInstanceProfile](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-autoscalinglaunchconfiguration) option:
```yaml
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - !Ref InstanceRole
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
....
  EBConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref EBApplicationName
      SolutionStackName: !Ref EBPlatform
      OptionSettings:
      - Namespace: 'aws:autoscaling:launchconfiguration'
        OptionName: IamInstanceProfile
        Value: !Ref InstanceProfile
```
As you can see we should specify the instance profile's name or its ARN, but AWS CFN Authentication accepts [rolename](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-authentication.html#cfn-cloudformation-authentication-rolename) only. Passing instance profile instead of role name will raise 403 error in `eb-activity.log`. Same issue occurs [several times](https://github.com/awsdocs/elastic-beanstalk-samples/search?q=%22AWS%3A%3ACloudFormation%3A%3AAuthentication%22+IamInstanceProfile&unscoped_q=%22AWS%3A%3ACloudFormation%3A%3AAuthentication%22+IamInstanceProfile) in this repo.
